sonar.projectKey=ApiTut-sonarqube
sonar.projectName=ApiTut-sonarqube
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8